### ISSUE TITLE
What if the process dies?

### ISSUE THREAD

**Issue by neerajwadhwani** [wasylni/pt_online_schema_change_pause#1]
Hi Marcin,

   Great plugin. I have a question though, what happens is the perl process dies before you want to manually delete the file and swap the tables? Is there an option to resume it somehow? I am assuming the triggers will still exists so the tables will still be consistent, correct?

Thanks

**Comment by wasylni** [comment]
Hi neerajwadhwani, 

no there is no auto-recovery option.
When the script fails I would advise to clear up and run it again (delete triggers and tables created by pt-online-schema-change). If you know what you are doing you can try to recover manually but first, read https://www.percona.com/blog/2016/06/30/rescuing-crashed-pt-online-schema-change-pt-archiver/
